#!/usr/bin/env node

import fs from 'fs'
import path from 'path'
import { initializeDatabase, exportAllSwatches } from '../src/db/init'

const dbPath = path.resolve('paint-swatcher.db')
const outPath = path.resolve('src/data/swatches.ts')

const db = initializeDatabase(dbPath)
const swatches = exportAllSwatches(db)

if (swatches.length === 0) {
  console.warn('⚠️  No swatches found in the database. Run `npm run seed -- --file scripts/initial-data.json` first if needed.')
}

const content = `// Generated by scripts/build-data.ts. Do not edit directly.

const swatchData = ${JSON.stringify(swatches, null, 2)}

export default swatchData
`

fs.writeFileSync(outPath, content, 'utf8')
console.log(`Generated ${path.relative(process.cwd(), outPath)} with ${swatches.length} swatches.`)

db.close()
